# Generated by Django 4.1.1 on 2022-09-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_review"),
    ]

    operations = [
        migrations.DeleteModel(name="Certificate",),
        migrations.DeleteModel(name="Portfolio",),
        migrations.DeleteModel(name="Testimonial",),
        migrations.RemoveField(model_name="userprofile", name="skills",),
        migrations.AlterField(
            model_name="review",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="review"),
        ),
        migrations.DeleteModel(name="Skill",),
    ]
